import React, { useState, useEffect } from 'react';
import { X, Layers, Users, Plus, Trash2 } from 'lucide-react';
import { api } from '../../lib/api';
import { Button } from '../../components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../../components/ui/Tabs';
import { toast } from 'react-hot-toast';
import { UniversalFormModal } from '../modals/UniversalFormModal';
import { DeleteConfirmCard } from '../../components/ui/DeleteConfirmCard';

export function AcademicDrawer({ isOpen, onClose, occupation }) {
  const [activeTab, setActiveTab] = useState('curriculum');
  
  // --- State ---
  const [levels, setLevels] = useState([]);
  const [curriculum, setCurriculum] = useState([]);
  const [selectedLevel, setSelectedLevel] = useState(null);
  const [batches, setBatches] = useState([]);
  const [academicYears, setAcademicYears] = useState([]);
  const [availableModules, setAvailableModules] = useState([]);

  // --- Modal States ---
  const [showLevelModal, setShowLevelModal] = useState(false);
  const [showBatchModal, setShowBatchModal] = useState(false);
  const [showModulePicker, setShowModulePicker] = useState(false);
  const [deleteId, setDeleteId] = useState(null); // For deleting batch or curriculum item
  const [deleteType, setDeleteType] = useState(null); // 'batch' or 'curriculum'
  const [isSubmitting, setIsSubmitting] = useState(false);

  // --- 1. Single Data Fetch Effect ---
  useEffect(() => {
    if (!isOpen || !occupation) return;

    const fetchData = async () => {
     
      try {
        const [levelsRes, batchesRes, yearsRes, modulesRes] = await Promise.all([
          api.get('/academics/levels', { params: { occupation_id: occupation.occupation_id } }),
          api.get('/academics/batches', { params: { occupation_id: occupation.occupation_id, limit: 50 } }),
          api.get('/academics/academic-years'),
                  api.get('/academics/modules/public', { params: { limit: 100 } }) 
        ]);
      

        setLevels(levelsRes.data || []);
        setBatches(batchesRes.rows || []);
        setAcademicYears(yearsRes.data || []);
        
        // FIX D: Use m_code as value to match backend requirement for adding to curriculum
        setAvailableModules((modulesRes.rows || []).map(m => ({
          value: m.m_code, // Backend expects m_code for curriculum
          label: `${m.m_code} - ${m.unit_competency}`
        })));

        if (levelsRes.data?.length > 0) {
          setSelectedLevel(levelsRes.data[0]);
        } else {
          setSelectedLevel(null);
          setCurriculum([]);
        }

      } catch (error) {
        console.error("Failed to fetch drawer data", error);
        toast.error("Failed to load data");
      }
    };

    fetchData();
  }, [isOpen, occupation]);

  // --- 2. Separate Effect for Curriculum ---
  useEffect(() => {
    if (selectedLevel) {
      fetchCurriculum(selectedLevel.level_id);
    } else {
      setCurriculum([]);
    }
  }, [selectedLevel]);

  const fetchCurriculum = async (levelId) => {
    try {
      const res = await api.get(`/academics/curriculum/${occupation.occupation_id}/${levelId}`);
      
      setCurriculum(res.data || []);
    } catch (error) {
      console.error("Failed to fetch curriculum", error);
      setCurriculum([]);
    }
  };

  // --- Schemas ---

  // FIX D: Updated to send m_code
  const modulePickerSchema = [
    {
      name: 'm_code', // Changed name to m_code
      label: 'Select Module',
      type: 'select',
      required: true,
      options: availableModules,
      fullWidth: true
    }
  ];

  // FIX C: Updated level_name to Select with ENUM values
  const levelSchema = [
    { name: 'level_id', label: 'Level Number (e.g., 1, 2, 3)', type: 'number', required: true },
    { 
      name: 'level_name', 
      label: 'Level Name', 
      type: 'select', // Changed from text
      required: true, 
      fullWidth: true,
      options: [
        { value: 'I', label: 'Level I (Year 1)' },
        { value: 'II', label: 'Level II (Year 2)' },
        { value: 'III', label: 'Level III (Year 3)' },
        { value: 'IV', label: 'Level IV (Year 4)' },
        { value: 'V', label: 'Level V (Year 5)' }
      ]
    }
  ];

  // FIX A: Removed batch_code (auto-generated by backend)
  const batchSchema = (years) => [
    // { name: 'batch_code', label: 'Batch Code', type: 'text', required: true }, // REMOVED
    { name: 'academic_year_id', label: 'Academic Year', type: 'select', required: true, options: years, fullWidth: true },
    { name: 'level_id', label: 'Level', type: 'select', required: true, options: levels.map(l => ({value: l.level_id, label: `Level ${l.level_id}`})), fullWidth: true },
    { name: 'capacity', label: 'Max Capacity', type: 'number', fullWidth: true } // Changed 'max_capacity' to 'capacity' to match model
  ];

  // --- Handlers ---

  // FIX D: Updated to use m_code
  const handleAddModule = async (formData) => {
    setIsSubmitting(true);
    try {
      await api.post('/academics/curriculum', {
        occupation_id: occupation.occupation_id,
        level_id: selectedLevel.level_id,
        m_code: formData.m_code // Send m_code
      });
      toast.success("Module added to curriculum");
      setShowModulePicker(false);
      fetchCurriculum(selectedLevel.level_id);
    } catch (error) {
      toast.error(error.response?.data?.message || "Failed to add module");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleSaveLevel = async (formData) => {
    setIsSubmitting(true);
    try {
      const payload = { ...formData, occupation_id: occupation.occupation_id };
      await api.post('/academics/levels', payload);
      toast.success("Level added");
      setShowLevelModal(false);
      const res = await api.get('/academics/levels', { params: { occupation_id: occupation.occupation_id } });
      setLevels(res.data || []);
      if (!selectedLevel) setSelectedLevel(res.data[0]); 
    } catch (error) {
      toast.error(error.response?.data?.message || "Failed");
    } finally { 
      setIsSubmitting(false); 
    }
  };

  // FIX A: Remove batch_code from payload before sending
  const handleSaveBatch = async (formData) => {
    setIsSubmitting(true);
    try {
      const { batch_code, ...payload } = formData; // Destructure to remove batch_code
      const finalPayload = { 
        ...payload, 
        occupation_id: occupation.occupation_id 
      };
      
      await api.post('/academics/batches', finalPayload);
      toast.success("Batch created");
      setShowBatchModal(false);
      const res = await api.get('/academics/batches', { params: { occupation_id: occupation.occupation_id, limit: 50 } });
      setBatches(res.rows || []);
    } catch (error) {
      toast.error(error.response?.data?.message || "Failed");
    } finally { 
      setIsSubmitting(false); 
    }
  };

  // FIX B: Unified Delete Handler
  const handleDelete = async () => {
    if(!deleteId) return;
    setIsSubmitting(true); // Reuse isSubmitting for loading state
    try {
      if (deleteType === 'batch') {
        await api.delete(`/academics/batches/${deleteId}`);
        toast.success("Batch deleted");
        const res = await api.get('/academics/batches', { params: { occupation_id: occupation.occupation_id, limit: 50 } });
        setBatches(res.rows || []);
      } else if (deleteType === 'curriculum') {
        await api.delete(`/academics/curriculum/${deleteId}`);
        toast.success("Module removed");
        if (selectedLevel) fetchCurriculum(selectedLevel.level_id);
      }
      setDeleteId(null);
      setDeleteType(null);
    } catch (error) { 
      toast.error("Failed to delete"); 
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-y-0 right-0 z-50 w-full md:w-[800px] bg-brand-background shadow-2xl border-l border-border-strong flex flex-col animate-in slide-in-from-right duration-300">
      <div className="p-6 border-b border-border-strong bg-brand-surface flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-brand-ink">{occupation.occupation_name}</h2>
          <p className="text-xs text-slate-500">{occupation.occupation_code} • Configure curriculum and batches</p>
        </div>
        <button onClick={onClose} className="text-slate-400 hover:text-red-500"><X size={24} /></button>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid w-full grid-cols-2 mb-6">
            <TabsTrigger value="curriculum" icon={<Layers size={16} />}>Curriculum</TabsTrigger>
            <TabsTrigger value="batches" icon={<Users size={16} />}>Batches</TabsTrigger>
          </TabsList>

          <TabsContent value="curriculum" className="space-y-4">
            <div className="flex justify-between items-center">
              <h3 className="font-semibold text-primary">Program Structure</h3>
              <Button size="sm" onClick={() => setShowLevelModal(true)}><Plus size={14} className="mr-2" /> Add Level</Button>
            </div>

            <div className="flex gap-4 h-[500px]">
              <div className="w-1/3 space-y-2">
                {levels.map((lvl) => (
                  <div
                    key={`${lvl.level_id}-${lvl.occupation_id}`} // Composite key
                    onClick={() => setSelectedLevel(lvl)}
                    className={`p-3 rounded-lg border cursor-pointer transition-all ${
                      selectedLevel?.level_id === lvl.level_id 
                      ? 'bg-brand-blue text-white border-brand-blue shadow-md' 
                      : 'bg-white border-border-strong hover:border-brand-blue/50'
                    }`}
                  >
                    <div className="font-bold text-sm">Level {lvl.level_id}</div>
                    <div className={`text-xs truncate ${selectedLevel?.level_id === lvl.level_id ? 'text-white/80' : 'text-slate-500'}`}>{lvl.level_name}</div>
                  </div>
                ))}
              </div>

              <div className="w-2/3 bg-white rounded-xl border border-border-strong p-4 overflow-y-auto">
                {selectedLevel ? (
                  <>
                    <div className="flex justify-between items-center mb-4">
                      <h4 className="font-bold text-brand-ink">Modules for Level {selectedLevel.level_id}</h4>
                      <Button size="xs" variant="outline" className="text-xs" onClick={() => setShowModulePicker(true)}>+ Add Module</Button>
                    </div>
                    {curriculum.length > 0 ? (
                      <div className="space-y-2">
                        {curriculum.map((item) => (
                          <div key={item.level_module_id} className="flex justify-between items-center p-3 bg-surface-muted rounded-lg">
                            <div>
                              <div className="font-bold text-sm text-brand-ink">{item.module?.unit_competency}</div>
                              <div className="text-xs font-mono text-slate-500">{item.module?.m_code}</div>
                            </div>
                            {/* FIX B: Added delete handler */}
                            <Button variant="ghost" size="icon" onClick={() => { setDeleteId(item.level_module_id); setDeleteType('curriculum'); }}><Trash2 size={14} className="text-red-500"/></Button>
                          </div>
                        ))}
                      </div>
                    ) : (
                      <div className="text-center text-slate-400 py-10">No modules assigned.</div>
                    )}
                  </>
                ) : (
                  <div className="h-full flex items-center justify-center text-slate-400">Select a level</div>
                )}
              </div>
            </div>
          </TabsContent>

          <TabsContent value="batches" className="space-y-4">
            <div className="flex justify-between items-center">
              <h3 className="font-semibold text-primary">Active Batches</h3>
              <Button size="sm" onClick={() => setShowBatchModal(true)}><Plus size={14} className="mr-2" /> New Batch</Button>
            </div>
            <div className="bg-white rounded-xl border border-border-strong overflow-hidden">
              <table className="w-full text-left text-sm">
                <thead className="bg-surface-muted border-b border-border-strong">
                  <tr>
                    <th className="p-3 font-bold text-primary">Code</th>
                    <th className="p-3 font-bold text-primary">Year</th>
                    <th className="p-3 font-bold text-primary">Level</th>
                    <th className="p-3 font-bold text-primary text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {batches.map((batch) => (
                    <tr key={batch.batch_id}>
                      <td className="p-3 font-medium text-brand-ink">{batch.batch_code}</td>
                      <td className="p-3 text-slate-600">{batch.academic_year?.academic_year_label || batch.academic_year?.year_name}</td>
                      <td className="p-3 text-slate-600">Level {batch.level?.level_id}</td>
                      <td className="p-3 text-right space-x-2">
                        {/* FIX B: Connected to unified delete handler */}
                        <Button variant="ghost" size="icon" onClick={() => { setDeleteId(batch.batch_id); setDeleteType('batch'); }}><Trash2 size={14} className="text-red-500" /></Button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </TabsContent>
        </Tabs>
      </div>

      {/* Modals */}
      <UniversalFormModal open={showLevelModal} onClose={() => setShowLevelModal(false)} onSubmit={handleSaveLevel} schema={levelSchema} title="Add New Level" isLoading={isSubmitting} />
      <UniversalFormModal open={showBatchModal} onClose={() => setShowBatchModal(false)} onSubmit={handleSaveBatch} schema={batchSchema(academicYears.map(y => ({value: y.academic_year_id, label: y.academic_year_label || y.year_name})))} title="Create New Batch" isLoading={isSubmitting} />
      <UniversalFormModal open={showModulePicker} onClose={() => setShowModulePicker(false)} onSubmit={handleAddModule} schema={modulePickerSchema} title="Add Module to Curriculum" isLoading={isSubmitting} />

      {/* Unified Delete Confirmation */}
    
    {deleteId && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-brand-ink/40 backdrop-blur-sm p-4 animate-in fade-in zoom-in-95 duration-200"
           onClick={() => { setDeleteId(null); setDeleteType(null); }}
        >
          <div className="w-full max-w-md shadow-2xl"
            onClick={(e) => e.stopPropagation()}>
          

           <DeleteConfirmCard
          open={!!deleteId}
          loading={isSubmitting}
          title={deleteType === 'batch' ? "Delete Batch?" : "Remove Module?"}
          description={deleteType === 'batch' ? "This will remove the batch record." : "This will remove the module from this level's curriculum."}
          onCancel={() => { setDeleteId(null); setDeleteType(null); }}
          onConfirm={handleDelete}
        />
          </div>
        </div>
      )}


    </div>
  );
}